build: false
shallow_clone: false
platform: 'x86'
clone_folder: c:\projects\chronos

branches:
  only:
    - master
    - 2.x

environment:
  global:
    PHP: "C:/PHP"

init:
  - SET PATH=C:\php\;%PATH%

install:
  - cd c:\
  - curl -fsS https://windows.php.net/downloads/releases/latest/php-7.2-nts-Win32-VC15-x86-latest.zip -o php.zip
  - 7z x php.zip -oc:\php
  - cd c:\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=mbstring >> php.ini
  - echo extension=intl >> php.ini
  - echo extension=fileinfo >> php.ini
  - cd C:\projects\chronos
  - appveyor DownloadFile https://getcomposer.org/composer.phar
  - php composer.phar install --prefer-dist --no-interaction --ansi --no-progress

test_script:
  - cd C:\projects\chronos
  - vendor\bin\phpunit.bat
